export default [
  {
    'id': 0,
    'name': `Fantastic Beasts`,
    'genre': `Comedies`,
    'poster_image': `img/fantastic-beasts-the-crimes-of-grindelwald.jpg`,
    'src': `https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4`,
    'preview_video_link': ``,
  },
  {
    'id': 1,
    'name': `Bohemian Rhapsody`,
    'genre': `Documentary`,
    'poster_image': `img/bohemian-rhapsody.jpg`,
    'src': `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
    'preview_video_link': ``,
  },
  {
    'id': 2,
    'name': `Macbeth`,
    'genre': `Dramas`,
    'poster_image': `img/macbeth.jpg`,
    'src': `https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4`,
    'preview_video_link': ``,
  },
  {
    'id': 3,
    'name': `Aviator`,
    'genre': `Romance`,
    'poster_image': `img/aviator.jpg`,
    'src': `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
    'preview_video_link': ``,
  },
  {
    'id': 4,
    'name': `We need to talk about Kevin`,
    'genre': `Thrillers`,
    'poster_image': `img/we-need-to-talk-about-kevin.jpg`,
    'src': `https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4`,
    'preview_video_link': ``,
  },
];
